### ISSUE TITLE
Revisit Black-Scholes model

### ISSUE THREAD

**Issue by jkbptrsn** [jkbptrsn/FinPy#3]
- Update docstrings
- Check analytical formulas
- Add finite difference solver to each instrument
- Add Monte-Carlo solver to each instrument (based on Euler scheme)
- Add Monte-Carlo solver to each instrument (based on exact discretization)
- Setup unit tests for each instrument

**Comment by PetersenJakob** [comment]
Type annotations
- Use Union for multiple type hints, e.g. Union[int, float]
- from typing import Union

**Comment by PetersenJakob** [comment]
Imports should be grouped in the following order:

1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

You should put a blank line between each group of imports.
https://peps.python.org/pep-0008/

**Comment by PetersenJakob** [comment]
Docstring conventions are covered by PEP 257
https://peps.python.org/pep-0257/

**Comment by PetersenJakob** [comment]
Use import statements for packages and modules only, not for individual classes or functions.

https://google.github.io/styleguide/pyguide.html

**Comment by PetersenJakob** [comment]
A docstring should be organized as a summary line. When writing more (encouraged), this must be followed by a blank line, followed by the rest of the docstring starting at the same cursor position as the first quote of the first line. 

https://google.github.io/styleguide/pyguide.html
